name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: thomashoneyman/setup-purescript@main
        with:
          purescript: "0.14.3"
          spago: "0.20.3"
          zephyr: "0.3.2"
          purs-tidy: "latest"

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
          path: |
            .spago
            output

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: "yarn"

      - name: Install yarn dependencies
        run: yarn ci

      - name: Build source
        run: spago build

      - name: Run tests
        run: spago test --no-install

      - name: Check formatting
        run: purs-tidy check src test

      - name: Run bundle
        run: yarn bundle

  preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_RYMDEN_2EA51 }}'
          projectId: rymden-2ea51
